LC/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from apps.administrador.views.login import cerrar_session
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset,
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'clave_enviado.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),
        url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
        url(r'^', include('apps.website.urls', namespace='website')),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),

    #url(r'^', include('restthumbnails.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/website/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from .views.login import IndexView, cerrar_session, cambiar_clave
from .views.HomeView import HomeView
from .views.AlojamientosView import AlojamientosView, AlojamientosCategorias, AlojamientosDetalle, get_cities_by_countryid
from .views.NoticiasView import NoticiasView
from .views.EstudiaTrabajaView import EstudiaTrabajaView
from .views.InstitucionView import InstitucionView, InstitucionDetalle

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),
    url(r'^cambiar_clave/$', cambiar_clave, name='cambiar_clave'),

    #alojamientos
    url(r'^alojamientos/',
        include([
            url(r'^$', AlojamientosView.as_view(), name='alojamientos'),
            url(
                r'^categorias$',
                AlojamientosCategorias.as_view(),
            name='alojamientos-categorias'),
            url(
                r'^detail/(?P<pk>[0-9]+)/$',
                AlojamientosDetalle.as_view(),
                name='alojamientos-detail'),
            url(
                r'^get_cities/$',
                get_cities_by_countryid,
                name='obtener-ciudades'),
        ])
    ),
    #noticias
    url(r'^noticias/', NoticiasView.as_view(), name='noticias'),
    url(r'^estudia_trabaja/', EstudiaTrabajaView.as_view(), name='estudia_trabaja'),
    #instituciones
    url(r'^instituciones/',
        include([
            url(r'^$', InstitucionView.as_view(), name='instituciones'),
            url(
            r'^detail/(?P<pk>[0-9]+)/$',
            InstitucionDetalle.as_view(),
            name='instituciones-detail')
        ])
    ),
]

apps/administrador/models.py
import os
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from sorl.thumbnail import ImageField


def path_and_rename(path, filename):
    file_root, file_ext = os.path.splitext(filename)
    filename = '{}{}'.format(get_random_string(20).lower(), file_ext)
    
    return os.path.join(path, filename)


class Modelo(models.Model):

    class Meta:
        abstract            = True
        get_latest_by       = 'updated_at'
        ordering            = ('-updated_at', '-created_at',)
        default_permissions = ('add', 'change', 'delete', 'view')


class Paises(models.Model):
    id = models.CharField(max_length=3, primary_key=True, verbose_name=_('Codigo pais'))
    pais = models.CharField(max_length=60, null=False, blank=False,verbose_name=_('Pais'))
    #region = models.CharField(max_length=30, null=False, blank=False, verbose_name=_('Region'))

    def __str__(self):
        return self.pais

    class Meta:
        db_table            = 'paises'
        verbose_name        = _('Pais')
        verbose_name_plural = _('Paises')
        get_latest_by       = 'pais'
        ordering            = ('pais',)

        permissions = (
            ("view_paises", "Can view Pais"),
            ("detail_paises", "Can detail Pais"),
        )

"""
class Estados(models.Model):
    estado = models.CharField(max_length=60, null=False, blank=False,verbose_name=_('Estado'))
    pais = models.ForeignKey(Paises, on_delete=models.CASCADE)

    class Meta:
        db_table            = 'estados'
        verbose_name        = _('Estado')
        verbose_name_plural = _('Estados')
        get_latest_by       = 'estado'
        ordering            = ('estado',)

        permissions = (
            ("view_estados", "Can view Estado"),
            ("detail_estados", "Can detail Estado"),
        )
"""

class Ciudades(models.Model):
    ciudad = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Ciudad'))
    #estado = models.ForeignKey(Estados, on_delete=models.CASCADE)
    pais = models.ForeignKey(Paises, on_delete=models.CASCADE)

    def __str__(self):
        return self.ciudad

    class Meta:
        db_table            = 'ciudades'
        verbose_name        = _('Ciudad')
        verbose_name_plural = _('Ciudades')
        get_latest_by       = 'ciudad'
        ordering            = ('ciudad',)

        permissions = (
            ("view_ciudades", "Can view Ciudad"),
            ("detail_ciudades", "Can detail Ciudad"),
        )


class UsuariosManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given username must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Usuarios(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'email'
    #REQUIRED_FIELDS = ['dni', 'genero', 'nacimiento', 'telefono']

    GENERO_CHOICES = (
        ('m', _('Masculino')),
        ('f', _('Femenino')),
    )
    TIPO_USUARIO = (
        ('LC', 'LC'),
        ('E', _('Estudiante')),
        ('I', _('Institucion educativa')),
        ('A', _('Arrendatarios')),
    )

    def rename_foto(self, filename):
        return path_and_rename("usuarios", filename)

    nombre       = models.CharField(max_length=100, null=True, blank=True, verbose_name=_('Nombre'))
    apellido     = models.CharField(max_length=100, null=True, blank=True, verbose_name=_('Apellido'))
    email        = models.EmailField(max_length=80, null=False, blank=False, db_index=True, unique=True, verbose_name =_('Correo Electronico'))

    # documento nacional de identidad
    dni          = models.CharField(max_length=15, null=True, blank=True, db_index=True, unique=True, verbose_name=_('Documento de Identidad'))
    genero       = models.CharField(choices=GENERO_CHOICES, max_length=15, null=True, blank=True, verbose_name=_('Genero'))
    nacimiento   = models.DateField(null=True, blank=True, verbose_name=_('Fecha de Nacimiento'))
    direccion    = models.TextField(max_length=250, null=True, blank=True, verbose_name=_('Dirección'))
    telefono     = models.CharField(max_length=20, null=True, blank=True, verbose_name=_('Telefono'))
    
    foto         = models.FileField(max_length=200, null=True, blank=True, upload_to=rename_foto, verbose_name=_('Imagen'))
    pais         = models.ForeignKey(Paises, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('Pais de Residencia'))
    tipo_usuario = models.CharField(max_length=2, default='LC')
    activo       = models.BooleanField(_('Activo'), default=False)
    #username_validator = UnicodeUsernameValidator() if six.PY3 else ASCIIUsernameValidator()

    #username = models.CharField(
    #    _('username'),
    #    max_length=150,
    #    help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
    #    validators=[username_validator],
    #)

    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    objects = UsuariosManager()

    def __str__(self):
        return str(self.nombre) + ' ' + str(self.apellido)

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def get_email_user(self):
        """
        Retorna el correo para que sea usado posteriormente
        """
        return self.email

    class Meta:
        db_table = 'usuarios'
        verbose_name = _('Usuario')
        verbose_name_plural = _('Usuarios')

        permissions = (
            ("view_usuarios", "Can view Usuario"),
            ("detail_usuarios", "Can detail Usuario"),
        )


class Multimedia(models.Model):
    
    archivo           = models.CharField(null=False, blank=False, max_length=80)
    nombre_archivo    = models.CharField(null=False, blank=False, max_length=80)
    sm                = models.CharField(null=False, blank=False, max_length=80)
    md                = models.CharField(null=False, blank=False, max_length=80)
    lg                = models.CharField(null=False, blank=False, max_length=80)
    tipo_archivo      = models.CharField(null=False, blank=False, max_length=1)
    titulo            = models.CharField(null=False, blank=False, max_length=120)
    texto_alternativo = models.CharField(null=False, blank=False, max_length=100)
    path              = models.CharField(null=False, blank=False, max_length=100, verbose_name=_('Nombre directorio'))
    
    created_at        = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at        = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    def __str__(self):
        return self.nombre_archivo

    # reescribir el metodo save para dejar toda la parte de multimedia lista para que sea usada por las views y los
    #templates
    #def save(self, *args, **kwargs):
    #    pass

    class Meta:
        db_table            = 'multimedia'
        verbose_name        = _('Multimedia')
        verbose_name_plural = _('Multimedias')


class Categorias(Modelo):

    nombre     = models.CharField(max_length=100, null=False, blank=False, verbose_name=_('Nombre'))
    categoria  = models.ForeignKey("self", on_delete=models.DO_NOTHING)

    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    def __str__(self):
        return self.nombre

    class Meta:
        db_table            = 'categorias'
        verbose_name        = _('Categoria')
        verbose_name_plural = _('Categorias')

        permissions = (
            ("view_categorias", "Can view Categoria"),
            ("detail_categorias", "Can detail Categoria"),
        )


class BannersUbicacion(Modelo):

apps/alojamiento/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.utils.translation import ugettext_lazy as _
from apps.administrador.models import Servicios, Multimedia, Usuarios


class Recargos(models.Model):

    monto      = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False, verbose_name=_('Monto'))
    mes        = JSONField(null=False, blank=False, verbose_name=_('Mes'))
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'recargos'
        verbose_name        = _('Recargo')
        verbose_name_plural = _('Recargos')

        permissions = (
            ("view_recargos", "Can view Recargo"),
            ("detail_recargos", "Can detail Recargo"),
        )

class Inmuebles_tipo(models.Model):
    descripcion = models.CharField(max_length=60, null=True, blank=True)
    activo = models.BooleanField(null=False, blank=False, default=True, verbose_name=_('Activo'))

    
    created_at  = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at  = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))
    

class Inmuebles(models.Model):    
    descripcion = models.TextField()
    normas = models.TextField(null=True, blank=True)
    precio_lc = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    precio_sede = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    precio_semanal = models.BooleanField(default=True, blank=False, null=False)
    activo = models.BooleanField(default=False)
    servicios = models.ManyToManyField(Servicios)
    arrendatario = models.ForeignKey(Usuarios)
    archivo = models.ManyToManyField(Multimedia)
    recargo = models.ForeignKey(Recargos, on_delete=models.PROTECT,null=True, blank=True)
    tipo_inmuebles = models.ForeignKey(Inmuebles_tipo, on_delete=models.PROTECT,null=True, blank=True)

    created_at     = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    update_at      = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'inmuebles'
        verbose_name        = _('Inmueble')
        verbose_name_plural = _('Inmuebles')

        permissions = (
            ("view_inmuebles", "Can view Inmueble"),
            ("detail_inmuebles", "Can detail Inmueble"),
        )

class Mobiliarios(models.Model):

    descripcion = models.TextField(max_length=80, verbose_name=_('Descripción'))
    
    created_at  = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at  = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'mobiliarios'
        verbose_name        = _('Mobiliario')
        verbose_name_plural = _('Mobiliarios')

        permissions = (
            ("view_mobiliarios", "Can view Mobiliario"),
            ("detail_mobiliarios", "Can detail Mobiliario"),
        )


class Inmuebles_mobiliario(models.Model):

    cantidad   = models.IntegerField(default=0, verbose_name=_('Cantidad'))
    mobiliario = models.ForeignKey(Mobiliarios, verbose_name=_('Mobiliario'))
    inmueble   = models.ForeignKey(Inmuebles, verbose_name=_('Inmueble'))
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'inmuebles_mobiliario'
        verbose_name        = _('Inmueble Mobiliario')
        verbose_name_plural = _('Inmuebles Mobiliario')

        permissions = (
            ("view_inmuebles_mobiliario", "Can view Inmueble Mobiliario"),
            ("detail_inmuebles_mobiliario", "Can detail Inmueble Mobiliario"),
        )

apps/alojamiento/views.py
from django.shortcuts import render

# Create your views here.

apps/website/views/HomeView.py
# Dependencias Django
from django.conf import settings

# Dependencias
from braces.views import LoginRequiredMixin, PermissionRequiredMixin

from django.views.generic.base import TemplateView

# Vista Generica
from ..vista import Vista, DetailView, CreateView, UpdateView, DeleteView

# Formularios
#from ..forms.HomeForm import HomeForm

# Modelos
#from ..models import Usuarios


class HomeView(Vista, TemplateView):
    template_name = "home.html"

apps/website/templates/alojamientos_categorias.html
{% extends 'layouts/website.html' %}
{% load staticfiles %}

{% block title %}
    Alojamientos 
{% endblock title %}

{% block contenido %}
		
	<div class="container-fluid">
		<div class="col-xs-12 text-center">
			<h1 class="texto-azul" style="font-weight:bold;">
				<i>{{ _('¿Qué quieres estudiar y donde?') }}</i>
			</h1>
			<p>
				{{ _('Utiliza nuestras herramientas de búsqueda y encuentra el programa ideal para ti') }}
			</p>
		</div>
		<img src="{% static 'img/img_buscador.jpg' %}" class="img-responsive" style="max-width:100%;margin: auto;">
	</div>		
	<div class="verde">
		<div class="container">
			<div class="row" style="padding: 10px">
				<form action="#">
					<div class="col-md-2 col-xs-12" style="padding:10px;">
						<select name="tipos_alojamientos" class="form-control campo selectpicker" id="id_tipos_alojamientos" required="" placeholder="tipos_alojamiento" tabindex="-98">
							<option value="" selected="">... Seleccione</option>
							{% for tipos in tipos_alojamientos %}
								<option value="{{ tipos.id }}">{{ tipos.nombre }}</option>
							{% endfor %}
						</select>
					</div>					
					<div class="col-md-2 col-xs-12" style="padding:10px;">
						<select name="precios" class="form-control campo selectpicker" id="id_precios" required="" placeholder="precios" tabindex="-98">
							<option value="" selected="">... Seleccione</option>
							{% for precio in precios %}
								<option value="{{ precio.id }}">{{ precio.nombre }}</option>
							{% endfor %}
						</select>
					</div>					
					<div class="col-md-2 col-xs-12" style="padding:10px;">
						<select name="servicios" class="form-control campo selectpicker" id="id_servicios" required="" placeholder="servicios" tabindex="-98">
							<option value="" selected="">Servicios</option>
							{% for servicio in servicios %}
								<option value="{{ servicio.id }}">{{ servicio.nombre }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="col-md-2 col-xs-12" style="padding:10px;">
						<select name="paises" class="form-control campo selectpicker" id="id_paises" required="" placeholder="paises" tabindex="-98">
							<option value="" selected="">... Seleccione</option>
							{% for pais in paises %}
								<option value="{{ pais.id }}">{{ pais.nombre }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="col-md-2 col-xs-12" style="padding:10px;">
						<select name="ciudades" class="form-control campo selectpicker" id="id_ciudades" required="" placeholder="ciudades" tabindex="-98">
							<option value="" selected="">... Seleccione</option>
							{% for ciudad in ciudades %}
								<option value="{{ ciudad.id }}">{{ ciudad.nombre }}</option>
							{% endfor %}
						</select>
					</div>
					<div class="col-md-2 col-xs-12" style="padding:10px;">
						<input type="button" id="btnBuscar" class="btn btn-default btn-" value="BUSCAR">
					</div>
				</form>
			</div>
		</div>
	</div>
	
	<div class="container-fluid" style="margin-top: 10px">
		<h4 style="margin-left: 35px;">
			Alojamientos/Resultado de búsquedas
		</h4>

		<div class="row" style="margin-top: 40px;">
			<div class="col-md-4 categorias">
				<div class="categorias-item-content">
					<div class="categorias-item-img">
						<div class="owl-carousel"  data-plugin-options='{"items": 1, "singleItem": false, "pagination": false, "autoPlay": true}'>
							<a class="item "  style="text-decoration:none;color:#7e8998;font-weight:bold;"  href="{% url 'website:alojamientos-detail' 1%}" data-lightbox="informatica" data-title="imagen">
								<img src="{% static 'img/alojamientos/hab.png' %}" class="img-responsive" width="100%" style="margin:auto;height:270px"/>
							</a>
						</div>
					</div>
					<div class="categorias-item-text">
						<div class="row">
							<div class="col-md-6">
								<p>Apartaestudio</p>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
							</div>
							<div class="col-md-6 text-right">
								<p>Canada / Toronto</p>
								<a href="#">
									<i class="fa fa-heart fa-2x text-center favorito"></i>
								</a>
							</div>
						</div>
						
					</div>
					
				</div>
					<div class="categorias-item-price verde">
						<p>$160</p>
					</div>
			</div>
			<div class="col-md-4 categorias">
				<div class="categorias-item-content">
					<div class="categorias-item-img">
						<div class="owl-carousel"  data-plugin-options='{"items": 1, "singleItem": false, "pagination": false, "autoPlay": true}'>
							<a class="item "  style="text-decoration:none;color:#7e8998;font-weight:bold;"  href="{% url 'website:alojamientos-detail' 2%}" data-lightbox="informatica" data-title="imagen">
								<img src="{% static 'img/alojamientos/hab.png' %}" class="img-responsive" width="100%" style="margin:auto;height:270px"/>
							</a>
							<a class="item "  style="text-decoration:none;color:#7e8998;font-weight:bold;"  href="#" data-lightbox="informatica" data-title="imagen">
								<img src="{% static 'img/alojamientos/apartamentos.png' %}" class="img-responsive" width="100%" style="margin:auto;height:270px"/>
							</a>
						</div>
					</div>
					<div class="categorias-item-text">
						<div class="row">
							<div class="col-md-6">
								<p>Apartaestudio</p>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
							</div>
							<div class="col-md-6 text-right">
								<p>Canada / Toronto</p>
								<a href="#">
									<i class="fa fa-heart fa-2x text-center no-favorito"></i>
								</a>
							</div>
						</div>
						
					</div>
					
				</div>
					<div class="categorias-item-price verde">
						<p>$160</p>
					</div>
			</div>
			<div class="col-md-4 categorias">
				<div class="categorias-item-content">
					<div class="categorias-item-img">
						<div class="owl-carousel"  data-plugin-options='{"items": 1, "singleItem": false, "pagination": false, "autoPlay": true}'>
							<a class="item "  style="text-decoration:none;color:#7e8998;font-weight:bold;"  href="{% url 'website:alojamientos-detail' 3%}" data-lightbox="informatica" data-title="imagen">
								<img src="{% static 'img/alojamientos/hab.png' %}" class="img-responsive" width="100%" style="margin:auto;height:270px"/>
							</a>
						</div>
					</div>
					<div class="categorias-item-text">
						<div class="row">
							<div class="col-md-6">
								<p>Apartaestudio</p>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
							</div>
							<div class="col-md-6 text-right">
								<p>Canada / Toronto</p>
								<a href="#">
									<i class="fa fa-heart fa-2x text-center no-favorito"></i>
								</a>
							</div>
						</div>
						
					</div>
					
				</div>
					<div class="categorias-item-price verde">
						<p>$160</p>
					</div>
			</div>
		</div>
		
		<div class="row" style="margin: auto; text-align: center">
			<ul class="pagination">
				<li><a href="#"> < </a></li>
				<li><a href="#">1</a></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">5</a></li>
				<li><a href="#"> > </a></li>
			</ul>
		</div>
	</div>
{% endblock contenido %}

{% block css %}
	<style type="text/css">
		.campo button {
			color: #333;
			background: #f0f0f0;
			border: 1px solid #f0f0f0;
		}

		.campo button:hover {
			color: #fff;
			background: #333;
			border: 1px solid #333;
		}
		.favorito{
			color: #C3D245;
		}
		.no-favorito{
			color: #8A8A8A;
		}
		
	</style>
{% endblock %}

{% block js%}
<script type="text/javascript">
$(function(){

	$("#id_paises").on('change', function(){
        console.log('djfsd');
        var pais_id = $('#id_paises').val();
        if(pais_id == ''){
            $('#id_ciudades').html('').append('<option value=""> {{_("Ciudad")}} </option>');
            return false;
        }

        $.ajax({
            dataType: 'json',
            method: 'POST',
            url: '/alojamientos/get_cities/',
            data: {
                pais: pais_id,
                csrfmiddlewaretoken: '{{ csrf_token  }}'
            },
            success: function (r) {
                console.log(r);
                $('#id_ciudades').html('').append('<option value=""> {{_("Ciudad")}} </option>');
                //recorriendo las ciudades rellenando el select ciudades 
                $.each(valor, function(id, v){
                    $('#id_ciudades').append('<option value="' + id + '">' + v + '</option>');
                });

            }
        });
    });
	
	$('.owl-carousel').owlCarousel({
		loop:true, 
		margin:10, 
		nav:true, 
		items:1,
		navigation:true,
		navigationText: [
        	"<i class='fa fa-chevron-left' style='color:#fff'></i>",
        	"<i class='fa fa-chevron-right'></i>"
        ],
	});

	$( ".owl-prev").html('<i class="fa fa-chevron-left"></i>');
 	$( ".owl-next").html('<i class="fa fa-chevron-right"></i>');
});
</script>
{% endblock js%}

{% block js %}
<script type="text/javascript">

$(function() {
    
    
    
});
</script>
{% endblock %}

apps/website/templates/clave_formulario.html
{% extends 'inicio_sesion.html' %}

{% block center %}
    <form method="post">
        {% csrf_token %}
        <p style="font-size:17px;">Ingresa tu correo y te enviaremos las instrucciones para restaurar tu contraseña.</p>
        <label id="email" for="id_email"> {{ form.email }}</label>
        <center>
        	<input class="btn submitlogin" type="submit" value="Restablecer Contraseña" style="width:60%;"/> 
        </center>
    </form>
<style type="text/css">
	#email{width: 75% !important;}
	#id_email{margin-bottom: 5px;}
	.login_wrapper{max-width: 600px !important;}
</style>
{% endblock %}