LC/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from apps.administrador.views.login import cerrar_session
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset,
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'clave_enviado.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),
        url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
        url(r'^', include('apps.website.urls', namespace='website')),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),

    #url(r'^', include('restthumbnails.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/administrador/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from .views.login import IndexView, cerrar_session, Cambiar_claveView, AceptarTerminosView

from .views.AgradecimientosView import Agradecimientos, AgradecimientosDetail, AgradecimientosCreate, AgradecimientosUpdate, AgradecimientosDelete
from .views.BannersView import Banners, BannersDetail, BannersCreate, BannersUpdate, BannersDelete
from .views.CategoriasView import Categorias, CategoriasCreate, CategoriasArbol
from .views.EstudiaTrabajaView import EstudiaTrabaja, EstudiaTrabajaDetail, EstudiaTrabajaCreate, EstudiaTrabajaUpdate, EstudiaTrabajaDelete
from .views.InformacionView import Informacion, InformacionDetail, InformacionCreate, InformacionUpdate, InformacionDelete
from .views.MultimediaView import MultimediaView, MultimediaInfoView, MultimediaListaView
from .views.OficinasView import Oficinas, OficinasDetail, OficinasCreate, OficinasUpdate, OficinasDelete, OficinasCiudades, OficinasMutimedia
from .views.Oportunidad_empleoView import Oportunidad_empleo, Oportunidad_empleoDetail, Oportunidad_empleoCreate, Oportunidad_empleoUpdate, Oportunidad_empleoDelete
from .views.Oportunidad_empleo_postuladosView import Oportunidad_empleo_postulados, Oportunidad_empleo_postuladosDetail, Oportunidad_empleo_postuladosCreate, Oportunidad_empleo_postuladosUpdate, Oportunidad_empleo_postuladosDelete
from .views.PerfilesView import Perfiles, PerfilesDetail, PerfilesCreate, PerfilesUpdate, PerfilesDelete, PerfilesArbol
from .views.Preguntas_frecuentesView import Preguntas_frecuentes, Preguntas_frecuentesDetail, Preguntas_frecuentesCreate, Preguntas_frecuentesUpdate, Preguntas_frecuentesDelete
from .views.Quienes_somosView import Quienes_somos, Quienes_somosCreate, Quienes_somosUpdate
from .views.Responsabilidad_socialView import Responsabilidad_social, Responsabilidad_socialDetail, Responsabilidad_socialCreate, Responsabilidad_socialUpdate, Responsabilidad_socialDelete
from .views.ServiciosView import Servicios, ServiciosDetail, ServiciosCreate, ServiciosUpdate, ServiciosDelete, ServiciosTipo
#from .views.SocialView import Social, SocialDetail, SocialCreate, SocialUpdate, SocialDelete
from .views.TestimoniosView import Testimonios, TestimoniosDetail, TestimoniosCreate, TestimoniosUpdate, TestimoniosDelete
from .views.UbicacionCategoriasView import UbicacionCategorias, UbicacionCategoriasDetail, UbicacionCategoriasCreate, UbicacionCategoriasUpdate, UbicacionCategoriasDelete
from .views.UbicacionView import Ubicacion, UbicacionPaisCreate, UbicacionCiudadCreate, UbicacionCiudades
from .views.UsuariosView import Usuarios, UsuariosDetail, UsuariosCreate, UsuariosUpdate, UsuariosDelete
from .views.SugerenciasView import Sugerencias, SugerenciasDetail, SugerenciasCreate, SugerenciasUpdate, SugerenciasDelete
from .views.AlojamientosView import Alojamientos, AlojamientosDetail, AlojamientosCreate, AlojamientosUpdate, AlojamientosDelete
from .views.EventosView import Eventos, EventosDetail, EventosCreate, EventosUpdate, EventosDelete
from .views.InstitucionesView import Instituciones, InstitucionesDetail, InstitucionesCreate, InstitucionesUpdate, InstitucionesDelete
from .views.NoticiaAdminView import NoticiaAdmin, NoticiaAdminDetail, NoticiaAdminCreate, NoticiaAdminUpdate, NoticiaAdminDelete

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),
    url(r'^cambiar_clave/$', Cambiar_claveView.as_view(), name='cambiar_clave'),

    url(r'^aceptar-terminos/$', AceptarTerminosView.as_view(), name='aceptar-terminos'),

    #usuarios
    url(r'^usuarios/', include([
        url(r'^$',                       Usuarios.as_view(),       name='usuarios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', UsuariosDetail.as_view(), name='usuarios-detail'),
        url(r'^create/$',                UsuariosCreate.as_view(), name='usuarios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', UsuariosUpdate.as_view(), name='usuarios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', UsuariosDelete.as_view(), name='usuarios-delete'),
    ])),

    url(r'^perfiles/', include([
        url(r'^$',                       Perfiles.as_view(),       name='perfiles'),
        url(r'^detail/(?P<pk>[0-9]+)/$', PerfilesDetail.as_view(), name='perfiles-detail'),
        url(r'^create/$',                PerfilesCreate.as_view(), name='perfiles-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', PerfilesUpdate.as_view(), name='perfiles-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', PerfilesDelete.as_view(), name='perfiles-delete'),
        url(r'^arbol/$',                 PerfilesArbol.as_view(), name='perfiles-arbol'),
    ])),
    
    url(r'^banners/', include([
        url(r'^$',                       Banners.as_view(),       name='banners'),
        url(r'^detail/(?P<pk>[0-9]+)/$', BannersDetail.as_view(), name='banners-detail'),
        url(r'^create/$',                BannersCreate.as_view(), name='banners-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', BannersUpdate.as_view(), name='banners-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', BannersDelete.as_view(), name='banners-delete'),
    ])),

    #testimonios
    url(r'^testimonios/', include([
        url(r'^$',                       Testimonios.as_view(),       name='testimonios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', TestimoniosDetail.as_view(), name='testimonios-detail'),
        url(r'^create/$',                TestimoniosCreate.as_view(), name='testimonios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', TestimoniosUpdate.as_view(), name='testimonios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', TestimoniosDelete.as_view(), name='testimonios-delete'),
    ])),
    
    #estudia_trabaja
    url(r'^estudia-trabaja/', include([
        url(r'^$',                       EstudiaTrabaja.as_view(),       name='estudia-trabaja'),
        url(r'^detail/(?P<pk>[0-9]+)/$', EstudiaTrabajaDetail.as_view(), name='estudia-trabaja-detail'),
        url(r'^create/$',                EstudiaTrabajaCreate.as_view(), name='estudia-trabaja-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', EstudiaTrabajaUpdate.as_view(), name='estudia-trabaja-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', EstudiaTrabajaDelete.as_view(), name='estudia-trabaja-delete'),
        #url(r'^ciudades/(?P<pk>[A-Z]{3})/$', EstudiaTrabajaCiudades.as_view(), name='estudia-trabaja-ciudades'),
    ])),
    
    #ubicacion
    url(r'^ubicacion/', include([
        url(r'^$',                           Ubicacion.as_view(),       name='ubicacion'),
        url(r'^pais/create/$',               UbicacionPaisCreate.as_view(), name='ubicacion-pais-create'),
        url(r'^ciudad/create/$',             UbicacionCiudadCreate.as_view(), name='ubicacion-ciudad-create'),
        url(r'^ciudades/(?P<pk>[A-Z]{3})/$', UbicacionCiudades.as_view(), name='ubicacion-ciudades'),
    ])),

    #categorias
    url(r'^categorias/', include([
        url(r'^$',                       Categorias.as_view(),       name='categorias'),
        url(r'^create/$',                CategoriasCreate.as_view(), name='categorias-create'),
        url(r'^arbol/$',                 CategoriasArbol.as_view(),  name='categorias-arbol'),
    ])),

    #servicios
    url(r'^servicios/', include([
        url(r'^$',                       Servicios.as_view(),       name='servicios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', ServiciosDetail.as_view(), name='servicios-detail'),
        url(r'^create/$',                ServiciosCreate.as_view(), name='servicios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', ServiciosUpdate.as_view(), name='servicios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', ServiciosDelete.as_view(), name='servicios-delete'),
        url(r'^add_tipo/$',              ServiciosTipo.as_view(),   name='servicios-tipo'),
    ])),
    
    #Quienes_somos
    url(r'^quienes_somos/', include([
        url(r'^$',                       Quienes_somos.as_view(),       name='quienes_somos'),
        url(r'^create/$',                Quienes_somosCreate.as_view(), name='quienes_somos-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', Quienes_somosUpdate.as_view(), name='quienes_somos-update'),
    ])),
    
    url(r'^responsabilidad_social/', include([
        url(r'^$',                       Responsabilidad_social.as_view(),       name='responsabilidad_social'),
        url(r'^detail/(?P<pk>[0-9]+)/$', Responsabilidad_socialDetail.as_view(), name='responsabilidad_social-detail'),
        url(r'^create/$',                Responsabilidad_socialCreate.as_view(), name='responsabilidad_social-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', Responsabilidad_socialUpdate.as_view(), name='responsabilidad_social-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', Responsabilidad_socialDelete.as_view(), name='responsabilidad_social-delete'),
    ])),

    url(r'^agradecimientos/', include([
        url(r'^$',                       Agradecimientos.as_view(),       name='agradecimientos'),
        url(r'^detail/(?P<pk>[0-9]+)/$', AgradecimientosDetail.as_view(), name='agradecimientos-detail'),
        url(r'^create/$',                AgradecimientosCreate.as_view(), name='agradecimientos-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', AgradecimientosUpdate.as_view(), name='agradecimientos-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', AgradecimientosDelete.as_view(), name='agradecimientos-delete'),
    ])),
    
    url(r'^multimedia/', include([
        url(r'^$',                       MultimediaView.as_view(),      name='multimedia'),
        url(r'^info/$',                  MultimediaInfoView.as_view(),  name='multimedia-info'),
        url(r'^refrescar/$',             MultimediaListaView.as_view(), name='multimedia-refrescar'),
    ])),

    url(r'^oficinas/', include([
        url(r'^$',                           Oficinas.as_view(),       name='oficinas'),

apps/administrador/forms/AgradecimientosForm.py
from django import forms

from ..models import Agradecimientos, Paises


class AgradecimientosForm(forms.ModelForm):

    pais = forms.ModelMultipleChoiceField(queryset=Paises.objects.all(), widget=forms.SelectMultiple(attrs={'class' : 'selectpicker','required':'required','multiple':'multiple','data-live-search':'true','data-width':'100%'}))


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for campo in self.fields:
            if campo == 'pais':
                continue

            self.fields[campo].widget.attrs.update({
                'class' : 'form-control campo',
                'placeholder' : self.fields[campo].label
            })

        self.fields['descripcion'].widget.attrs.update({'class' : 'textareaTiny'})


    def save(self, commit=True):
        instance = forms.ModelForm.save(self, False)

        old_save_m2m = self.save_m2m
        def save_m2m():
            old_save_m2m()
           
            instance.pais.clear() 
            for pais in self.cleaned_data['pais']:
                instance.pais.add(pais)

        self.save_m2m = save_m2m

        if commit:
            instance.save()
            self.save_m2m()

        return instance


    class Meta:
        model = Agradecimientos
        fields = ['pais', 'titulo', 'descripcion']
        widgets = {
            'descripcion': forms.Textarea(attrs={'class': 'form-control campo textareaTiny'})
        }

apps/administrador/forms/AlojamientosForm.py
from django import forms

from ..models import  Paises
from apps.alojamiento.models import Inmuebles, Inmuebles_tipo

class AlojamientosForm(forms.ModelForm):

    tipo_inmuebles = forms.ModelMultipleChoiceField(queryset=Inmuebles_tipo.objects.all(), widget=forms.SelectMultiple(attrs={'class' : 'selectpicker','required':'required','multiple':'multiple','data-live-search':'true','data-width':'100%'}))
    pais = forms.ModelMultipleChoiceField(queryset=Paises.objects.all(), widget=forms.SelectMultiple(attrs={'class' : 'selectpicker','required':'required','multiple':'multiple','data-live-search':'true','data-width':'100%'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for campo in self.fields:
            if campo == 'pais':
                continue

            self.fields[campo].widget.attrs.update({
                'class' : 'form-control campo',
                'placeholder' : self.fields[campo].label
            })
    

    def save(self, commit=True):
        instance = forms.ModelForm.save(self, False)

        old_save_m2m = self.save_m2m
        def save_m2m():
            old_save_m2m()
           
            instance.pais.clear() 
            for pais in self.cleaned_data['pais']:
                instance.pais.add(pais)

        self.save_m2m = save_m2m

        if commit:
            instance.save()
            self.save_m2m()

        return instance


    class Meta:
        model = Inmuebles
        
        fields = [
            'descripcion',
            'normas',
            'precio_lc',
            'precio_sede',
            'precio_semanal',
            'activo',
            'servicios',
            'arrendatario',
            'archivo',
            'recargo',
            'tipo_inmuebles',
        ]
        widgets = {
            'descripcion'    : forms.Textarea(attrs={'class': 'form-control campo', 'rows': 5, 'cols': 200, 'style': 'resize:none;'})
        }

apps/administrador/forms/BannersForm.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from ..models import Banners, Paises, BannersUbicacion


class BannersForm(forms.ModelForm): 
    
    pais = forms.ModelMultipleChoiceField(queryset=Paises.objects.all(), widget=forms.SelectMultiple(attrs={ 'class' : 'selectpicker show-menu-arrow form-control required' }))
    ubicacion = forms.ModelMultipleChoiceField(queryset=BannersUbicacion.objects.all(), widget=forms.SelectMultiple(attrs={ 'class' : 'selectpicker show-menu-arrow form-control required' }))

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

        for campo in self.fields:
            if campo == 'pais' or campo == 'ubicacion':
                continue

            self.fields[campo].widget.attrs.update({
                'class' : 'form-control campo',
                'placeholder' : self.fields[campo].label
            })


    def save(self, commit=True):
        instance = forms.ModelForm.save(self, False)

        old_save_m2m = self.save_m2m
        def save_m2m():
            old_save_m2m()
           
            instance.pais.clear() 
            for pais in self.cleaned_data['pais']:
                instance.pais.add(pais)

            instance.ubicacion.clear() 
            for ubicacion in self.cleaned_data['ubicacion']:
                instance.ubicacion.add(ubicacion)

        self.save_m2m = save_m2m

        if commit:
            instance.save()
            self.save_m2m()

        return instance


    class Meta:
        model = Banners
        fields = ['titulo', 'subtitulo', 'pais', 'ubicacion', 'multimedia', 'posicion', 'activo']
        widgets = {
            #'category': forms.SelectMultiple(attrs={ 'class' : 'selectpicker show-menu-arrow form-control required' })
        }

apps/administrador/forms/CategoriasForm.py
from django import forms

from ..models import Categorias


class CategoriasForm(forms.ModelForm):

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

        for campo in self.fields:
            self.fields[campo].widget.attrs.update({
                'class' : 'form-control campo',
                'placeholder' : self.fields[campo].label
            })

    class Meta:
        model = Categorias
        fields = ['nombre']

apps/administrador/forms/MultimediaForm.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from ..models import Multimedia


class MultimediaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for campo in self.fields:
            self.fields[campo].widget.attrs.update({
                'class' : 'form-control campo',
                'placeholder' : self.fields[campo].label
            })

    class Meta:
        model = Multimedia
        fields = ['email', 'pais', 'ciudad', 'direccion', 'iframe_ubicacion']

apps/administrador/templates/partials/botonera.html
<div class="col-sm-10 col-lg-6 col-lg-offset-3 col-md-6  col-md-offset-3" style="margin-bottom: 25px;margin-top: 25px;">
    <input type="submit" id="guardar" name="guardar" class="btn btn-default right btnAceptar" value="{{ _('Aceptar') }}">
    <input type="reset" id="limpiar" class="btn btn-warning right btnLimpiar" value="{{ _('Limpiar') }}">
</div>

apps/administrador/templates/partials/busqueda.html
{% block filtroDatatable%}{% endblock %}
{{ tabla.titulo }}
<table id="{{ tabla.id|default:"tabla" }}!" class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            {% for columna, ancho in tabla.columnas.items %}
            <th style="width: {{ ancho }}%;">{{ columna }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody></tbody>
    <tfoot>
        <tr>
            {% for columna, ancho in tabla.columnas.items %}
            <td style="width: {{ ancho }}%;">{{ columna }}</td>
            {% endfor %}
        </tr>
    </tfoot>
</table>

apps/administrador/templates/partials/menu.html
{% load staticfiles %}
<div class="col-md-3 left_col">
	<div class="left_col scroll-view">
		<div class="navbar nav_title" style="border: 0; height:auto;">
			<a href="{% url 'administrador:index' %}" class="site_title" style=" height:auto; padding-left:0px !important;">
				<center>
					<img src="{% static 'img/lc_blanco.png' %}" style='max-width:60%;padding:4px; '>
				</center>
			</a>
		</div>

		<div class="clearfix"></div>

		<br />

		<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
			<div class="menu_section">
				<ul class="nav side-menu">
					{% for MENU_ in MENU %}
						{% for element in MENU_ %}
						<li>
							{% if 'direccion' in element %}
							<a href="{% url element.direccion %}">
							{% else %}
							<a href="#{{ element.nombre|slugify }}">
							{% endif %}
								<i class="{{ element.icono }}" aria-hidden="true"></i> {{ element.nombre }}
								{% if element.menu %}
								<i class="fa fa-chevron-down flecha" aria-hidden="true"></i>
								{% endif %}
							</a>
							
							{% if element.menu %}
							<ul class="nav child_menu">
							{% for subelement in element.menu %}
								<li>
									{% if 'direccion' in subelement %}
									<a href="{% url subelement.direccion %}">
									{% else %}
									<a href="#{{ subelement.nombre|slugify }}">
									{% endif %}
										<i class="{{ subelement.icono }}" aria-hidden="true"></i> {{ subelement.nombre }}
									</a>
								</li>
							{% endfor %}
							</ul>
							{% endif %}

							<!-- ASI DEBE SER LA LISTA DE HIJOS  -->
						</li>
						{% endfor %}
					{% endfor %}
				</ul>
			</div>
		</div>
		<!-- /sidebar menu -->

		<!-- /menu footer buttons
		<div class="sidebar-footer hidden-small">
			<a data-toggle="tooltip" data-placement="top" title="Settings">
				<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
			</a>
			<a data-toggle="tooltip" data-placement="top" title="FullScreen">
				<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
			</a>
			<a data-toggle="tooltip" data-placement="top" title="Lock">
				<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
			</a>
			<a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
				<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
			</a>
		</div> -->
		<!-- /menu footer buttons -->
	</div>
</div>

apps/administrador/templates/partials/page-footer.html
<!--
	<footer>  footer content 
		<div class="pull-right">
			
		</div>
		<div class="clearfix"></div>
	</footer>
	 /footer content -->

apps/administrador/templates/partials/page-header.html
{% load staticfiles %}
<!-- top navigation -->
<div class="top_nav">
	<div class="nav_menu">
		<nav>
			<div class="nav toggle">
				<a id="menu_toggle"><i class="fa fa-bars"></i></a>
			</div>

			<ul class="nav navbar-nav navbar-right">
				<li class="" style="right: 13px;">
					<a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
						<i class="fa fa-user" style="margin:0 5px;"></i> {{ user.get_username }}
						<span class=" fa fa-caret-down"></span>
					</a>
					<ul class="dropdown-menu dropdown-usermenu pull-right">
						<li class="liusermenu"><a href="javascript:;"> Ir al Web site</a></li>
						<li class="liusermenu"><a href="/administrador/cambiar_clave"> Cambiar Contrase&ntilde;a</a></li>
						<li class="liusermenu">
							<a href="{% url 'administrador:cerrar_sesion' %}"> 
								<i class="fa fa-sign-out pull-right"></i> 
								Cerrar Sesi&oacute;n 
							</a>
						</li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</div>
<!-- /top navigation -->

apps/administrador/templates/partials/ubicacion.html
	<ul class="page-breadcrumb breadcrumb">
		<li>
			<a href="{% url 'administrador:index' %}">Inicio</a><i class="fa fa-circle"></i>
		</li>

		{% for ubi in ubicacion %}
		<li>
			<span>{{ ubi }}
			{% if not forloop.last %}
			<i class="fa fa-circle"></i>
			{% endif %}
			</span>
		</li>
		{% endfor %}
	</ul>