LC/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from apps.administrador.views.login import cerrar_session
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset,
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'clave_enviado.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),
        url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
        url(r'^', include('apps.website.urls', namespace='website')),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),

    #url(r'^', include('restthumbnails.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/administrador/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from .views.login import IndexView, cerrar_session, Cambiar_claveView, AceptarTerminosView

from .views.AgradecimientosView import Agradecimientos, AgradecimientosDetail, AgradecimientosCreate, AgradecimientosUpdate, AgradecimientosDelete
from .views.BannersView import Banners, BannersDetail, BannersCreate, BannersUpdate, BannersDelete
from .views.CategoriasView import Categorias, CategoriasCreate, CategoriasArbol
from .views.EstudiaTrabajaView import EstudiaTrabaja, EstudiaTrabajaDetail, EstudiaTrabajaCreate, EstudiaTrabajaUpdate, EstudiaTrabajaDelete
from .views.InformacionView import Informacion, InformacionDetail, InformacionCreate, InformacionUpdate, InformacionDelete
from .views.MultimediaView import MultimediaView, MultimediaInfoView, MultimediaListaView
from .views.OficinasView import Oficinas, OficinasDetail, OficinasCreate, OficinasUpdate, OficinasDelete, OficinasCiudades, OficinasMutimedia
from .views.Oportunidad_empleoView import Oportunidad_empleo, Oportunidad_empleoDetail, Oportunidad_empleoCreate, Oportunidad_empleoUpdate, Oportunidad_empleoDelete
from .views.Oportunidad_empleo_postuladosView import Oportunidad_empleo_postulados, Oportunidad_empleo_postuladosDetail, Oportunidad_empleo_postuladosCreate, Oportunidad_empleo_postuladosUpdate, Oportunidad_empleo_postuladosDelete
from .views.PerfilesView import Perfiles, PerfilesDetail, PerfilesCreate, PerfilesUpdate, PerfilesDelete, PerfilesArbol
from .views.Preguntas_frecuentesView import Preguntas_frecuentes, Preguntas_frecuentesDetail, Preguntas_frecuentesCreate, Preguntas_frecuentesUpdate, Preguntas_frecuentesDelete
from .views.Quienes_somosView import Quienes_somos, Quienes_somosCreate, Quienes_somosUpdate
from .views.Responsabilidad_socialView import Responsabilidad_social, Responsabilidad_socialDetail, Responsabilidad_socialCreate, Responsabilidad_socialUpdate, Responsabilidad_socialDelete
from .views.ServiciosView import Servicios, ServiciosDetail, ServiciosCreate, ServiciosUpdate, ServiciosDelete, ServiciosTipo
#from .views.SocialView import Social, SocialDetail, SocialCreate, SocialUpdate, SocialDelete
from .views.TestimoniosView import Testimonios, TestimoniosDetail, TestimoniosCreate, TestimoniosUpdate, TestimoniosDelete
from .views.UbicacionCategoriasView import UbicacionCategorias, UbicacionCategoriasDetail, UbicacionCategoriasCreate, UbicacionCategoriasUpdate, UbicacionCategoriasDelete
from .views.UbicacionView import Ubicacion, UbicacionPaisCreate, UbicacionCiudadCreate, UbicacionCiudades
from .views.UsuariosView import Usuarios, UsuariosDetail, UsuariosCreate, UsuariosUpdate, UsuariosDelete
from .views.SugerenciasView import Sugerencias, SugerenciasDetail, SugerenciasCreate, SugerenciasUpdate, SugerenciasDelete
from .views.AlojamientosView import Alojamientos, AlojamientosDetail, AlojamientosCreate, AlojamientosUpdate, AlojamientosDelete
from .views.EventosView import Eventos, EventosDetail, EventosCreate, EventosUpdate, EventosDelete
from .views.InstitucionesView import Instituciones, InstitucionesDetail, InstitucionesCreate, InstitucionesUpdate, InstitucionesDelete
from .views.NoticiaAdminView import NoticiaAdmin, NoticiaAdminDetail, NoticiaAdminCreate, NoticiaAdminUpdate, NoticiaAdminDelete

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),
    url(r'^cambiar_clave/$', Cambiar_claveView.as_view(), name='cambiar_clave'),

    url(r'^aceptar-terminos/$', AceptarTerminosView.as_view(), name='aceptar-terminos'),

    #usuarios
    url(r'^usuarios/', include([
        url(r'^$',                       Usuarios.as_view(),       name='usuarios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', UsuariosDetail.as_view(), name='usuarios-detail'),
        url(r'^create/$',                UsuariosCreate.as_view(), name='usuarios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', UsuariosUpdate.as_view(), name='usuarios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', UsuariosDelete.as_view(), name='usuarios-delete'),
    ])),

    url(r'^perfiles/', include([
        url(r'^$',                       Perfiles.as_view(),       name='perfiles'),
        url(r'^detail/(?P<pk>[0-9]+)/$', PerfilesDetail.as_view(), name='perfiles-detail'),
        url(r'^create/$',                PerfilesCreate.as_view(), name='perfiles-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', PerfilesUpdate.as_view(), name='perfiles-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', PerfilesDelete.as_view(), name='perfiles-delete'),
        url(r'^arbol/$',                 PerfilesArbol.as_view(), name='perfiles-arbol'),
    ])),
    
    url(r'^banners/', include([
        url(r'^$',                       Banners.as_view(),       name='banners'),
        url(r'^detail/(?P<pk>[0-9]+)/$', BannersDetail.as_view(), name='banners-detail'),
        url(r'^create/$',                BannersCreate.as_view(), name='banners-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', BannersUpdate.as_view(), name='banners-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', BannersDelete.as_view(), name='banners-delete'),
    ])),

    #testimonios
    url(r'^testimonios/', include([
        url(r'^$',                       Testimonios.as_view(),       name='testimonios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', TestimoniosDetail.as_view(), name='testimonios-detail'),
        url(r'^create/$',                TestimoniosCreate.as_view(), name='testimonios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', TestimoniosUpdate.as_view(), name='testimonios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', TestimoniosDelete.as_view(), name='testimonios-delete'),
    ])),
    
    #estudia_trabaja
    url(r'^estudia-trabaja/', include([
        url(r'^$',                       EstudiaTrabaja.as_view(),       name='estudia-trabaja'),
        url(r'^detail/(?P<pk>[0-9]+)/$', EstudiaTrabajaDetail.as_view(), name='estudia-trabaja-detail'),
        url(r'^create/$',                EstudiaTrabajaCreate.as_view(), name='estudia-trabaja-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', EstudiaTrabajaUpdate.as_view(), name='estudia-trabaja-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', EstudiaTrabajaDelete.as_view(), name='estudia-trabaja-delete'),
        #url(r'^ciudades/(?P<pk>[A-Z]{3})/$', EstudiaTrabajaCiudades.as_view(), name='estudia-trabaja-ciudades'),
    ])),
    
    #ubicacion
    url(r'^ubicacion/', include([
        url(r'^$',                           Ubicacion.as_view(),       name='ubicacion'),
        url(r'^pais/create/$',               UbicacionPaisCreate.as_view(), name='ubicacion-pais-create'),
        url(r'^ciudad/create/$',             UbicacionCiudadCreate.as_view(), name='ubicacion-ciudad-create'),
        url(r'^ciudades/(?P<pk>[A-Z]{3})/$', UbicacionCiudades.as_view(), name='ubicacion-ciudades'),
    ])),

    #categorias
    url(r'^categorias/', include([
        url(r'^$',                       Categorias.as_view(),       name='categorias'),
        url(r'^create/$',                CategoriasCreate.as_view(), name='categorias-create'),
        url(r'^arbol/$',                 CategoriasArbol.as_view(),  name='categorias-arbol'),
    ])),

    #servicios
    url(r'^servicios/', include([
        url(r'^$',                       Servicios.as_view(),       name='servicios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', ServiciosDetail.as_view(), name='servicios-detail'),
        url(r'^create/$',                ServiciosCreate.as_view(), name='servicios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', ServiciosUpdate.as_view(), name='servicios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', ServiciosDelete.as_view(), name='servicios-delete'),
        url(r'^add_tipo/$',              ServiciosTipo.as_view(),   name='servicios-tipo'),
    ])),
    
    #Quienes_somos
    url(r'^quienes_somos/', include([
        url(r'^$',                       Quienes_somos.as_view(),       name='quienes_somos'),
        url(r'^create/$',                Quienes_somosCreate.as_view(), name='quienes_somos-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', Quienes_somosUpdate.as_view(), name='quienes_somos-update'),
    ])),
    
    url(r'^responsabilidad_social/', include([
        url(r'^$',                       Responsabilidad_social.as_view(),       name='responsabilidad_social'),
        url(r'^detail/(?P<pk>[0-9]+)/$', Responsabilidad_socialDetail.as_view(), name='responsabilidad_social-detail'),
        url(r'^create/$',                Responsabilidad_socialCreate.as_view(), name='responsabilidad_social-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', Responsabilidad_socialUpdate.as_view(), name='responsabilidad_social-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', Responsabilidad_socialDelete.as_view(), name='responsabilidad_social-delete'),
    ])),

    url(r'^agradecimientos/', include([
        url(r'^$',                       Agradecimientos.as_view(),       name='agradecimientos'),
        url(r'^detail/(?P<pk>[0-9]+)/$', AgradecimientosDetail.as_view(), name='agradecimientos-detail'),
        url(r'^create/$',                AgradecimientosCreate.as_view(), name='agradecimientos-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', AgradecimientosUpdate.as_view(), name='agradecimientos-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', AgradecimientosDelete.as_view(), name='agradecimientos-delete'),
    ])),
    
    url(r'^multimedia/', include([
        url(r'^$',                       MultimediaView.as_view(),      name='multimedia'),
        url(r'^info/$',                  MultimediaInfoView.as_view(),  name='multimedia-info'),
        url(r'^refrescar/$',             MultimediaListaView.as_view(), name='multimedia-refrescar'),
    ])),

    url(r'^oficinas/', include([
        url(r'^$',                           Oficinas.as_view(),       name='oficinas'),

apps/alojamiento/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.utils.translation import ugettext_lazy as _
from apps.administrador.models import Servicios, Multimedia, Usuarios


class Recargos(models.Model):

    monto      = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False, verbose_name=_('Monto'))
    mes        = JSONField(null=False, blank=False, verbose_name=_('Mes'))
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'recargos'
        verbose_name        = _('Recargo')
        verbose_name_plural = _('Recargos')

        permissions = (
            ("view_recargos", "Can view Recargo"),
            ("detail_recargos", "Can detail Recargo"),
        )

class Inmuebles_tipo(models.Model):
    descripcion = models.CharField(max_length=60, null=True, blank=True)
    activo = models.BooleanField(null=False, blank=False, default=True, verbose_name=_('Activo'))

    
    created_at  = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at  = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))
    

class Inmuebles(models.Model):    
    descripcion = models.TextField()
    normas = models.TextField(null=True, blank=True)
    precio_lc = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    precio_sede = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    precio_semanal = models.BooleanField(default=True, blank=False, null=False)
    activo = models.BooleanField(default=False)
    servicios = models.ManyToManyField(Servicios)
    arrendatario = models.ForeignKey(Usuarios)
    archivo = models.ManyToManyField(Multimedia)
    recargo = models.ForeignKey(Recargos, on_delete=models.PROTECT,null=True, blank=True)
    tipo_inmuebles = models.ForeignKey(Inmuebles_tipo, on_delete=models.PROTECT,null=True, blank=True)

    created_at     = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    update_at      = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'inmuebles'
        verbose_name        = _('Inmueble')
        verbose_name_plural = _('Inmuebles')

        permissions = (
            ("view_inmuebles", "Can view Inmueble"),
            ("detail_inmuebles", "Can detail Inmueble"),
        )

class Mobiliarios(models.Model):

    descripcion = models.TextField(max_length=80, verbose_name=_('Descripción'))
    
    created_at  = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at  = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'mobiliarios'
        verbose_name        = _('Mobiliario')
        verbose_name_plural = _('Mobiliarios')

        permissions = (
            ("view_mobiliarios", "Can view Mobiliario"),
            ("detail_mobiliarios", "Can detail Mobiliario"),
        )


class Inmuebles_mobiliario(models.Model):

    cantidad   = models.IntegerField(default=0, verbose_name=_('Cantidad'))
    mobiliario = models.ForeignKey(Mobiliarios, verbose_name=_('Mobiliario'))
    inmueble   = models.ForeignKey(Inmuebles, verbose_name=_('Inmueble'))
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name=_('Fecha de Creación'))
    updated_at = models.DateTimeField(auto_now=True, editable=False, verbose_name=_('Fecha de Actualización'))

    class Meta:
        db_table            = 'inmuebles_mobiliario'
        verbose_name        = _('Inmueble Mobiliario')
        verbose_name_plural = _('Inmuebles Mobiliario')

        permissions = (
            ("view_inmuebles_mobiliario", "Can view Inmueble Mobiliario"),
            ("detail_inmuebles_mobiliario", "Can detail Inmueble Mobiliario"),
        )

apps/administrador/forms/AgradecimientosForm.py
from django import forms

from ..models import Agradecimientos, Paises


class AgradecimientosForm(forms.ModelForm):

    pais = forms.ModelMultipleChoiceField(queryset=Paises.objects.all(), widget=forms.SelectMultiple(attrs={'class' : 'selectpicker','required':'required','multiple':'multiple','data-live-search':'true','data-width':'100%'}))


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for campo in self.fields:
            if campo == 'pais':
                continue

            self.fields[campo].widget.attrs.update({
                'class' : 'form-control campo',
                'placeholder' : self.fields[campo].label
            })

        self.fields['descripcion'].widget.attrs.update({'class' : 'textareaTiny'})


    def save(self, commit=True):
        instance = forms.ModelForm.save(self, False)

        old_save_m2m = self.save_m2m
        def save_m2m():
            old_save_m2m()
           
            instance.pais.clear() 
            for pais in self.cleaned_data['pais']:
                instance.pais.add(pais)

        self.save_m2m = save_m2m

        if commit:
            instance.save()
            self.save_m2m()

        return instance


    class Meta:
        model = Agradecimientos
        fields = ['pais', 'titulo', 'descripcion']
        widgets = {
            'descripcion': forms.Textarea(attrs={'class': 'form-control campo textareaTiny'})
        }

apps/administrador/forms/CategoriasForm.py
from django import forms

from ..models import Categorias


class CategoriasForm(forms.ModelForm):

    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)

        for campo in self.fields:
            self.fields[campo].widget.attrs.update({
                'class' : 'form-control campo',
                'placeholder' : self.fields[campo].label
            })

    class Meta:
        model = Categorias
        fields = ['nombre']

apps/administrador/forms/SeccionesForm.py
from django import forms

from ..models import Secciones


class SeccionesForm(forms.ModelForm):
    
    class Meta:
        model = Secciones
        fields = ['nombre']

apps/administrador/templates/banners.html
{% extends 'layouts/default.html' %}
{% load static %}
{% load i18n %}

{% block contenido %}
	<div class="" role="tabpanel" data-example-id="togglable-tabs">
	  <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
		<li role="presentation" class="active">
			<a href="#contBanners" id="tabBanners" role="tab" data-toggle="tab" aria-expanded="true">Admnistrador de Banners</a>
		</li>
	  </ul>
	  
	  <div id="myTabContent" class="tab-content col-md-12 col-sm-12 col-xs-12">
		<div class="clearfix"></div>
		<div class="barra"></div>
		<div role="tabpanel" class="tab-pane fade active in col-md-12 col-sm-12 col-xs-12" id="contBanners" aria-labelledby="tabBanners">
			<div class="contenedorTab" style="display:none;">
          		<input type="button" class="btn btn-default right btnVolverListado" value="Volver al Listado" style="float:left;" ocultar="contenedorTab" mostrar="divListadoForm">
	    		<div class="clearfix"></div>
	    		
				<div class="row">
					<form id="formulario" method="post" accept-charset="utf-8">
						{% csrf_token %}

						<div class="col-md-6 col-sm-6 col-xs-12">
		    				<label for="id_activo" style="float:left; margin:10px; font-weight:bold;">  {{ form.activo.label }} </label>
							{{ form.activo }}
	    				</div>
	    				
	    				<div class="clearfix"></div>

						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="obj tituloselect">
								{{ form.pais.label }}
							</div>

							<div style="background: #eaeaea; margin-top: -10px; padding: 5px; width: 100%;">
								{{ form.pais }}
							</div>
						</div>

						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="obj tituloselect"> {{ form.ubicacion.label }} </div>

							<div style="background: #eaeaea; margin-top: -10px; padding: 5px; width: 100%;">
								{{ form.ubicacion }}
							</div>
						</div>

						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="obj tituloselect">
								{{ form.titulo.label }}
							</div>

							<div style="background: #eaeaea; margin-top: -10px; padding: 5px; width: 100%;">	
								{{ form.titulo }}
							</div>
						</div>

						<div class="col-md-4 col-sm-4 col-xs-12">
							<div class="obj tituloselect">
								{{ form.subtitulo.label }}
							</div>

							<div style="background: #eaeaea; margin-top: -10px; padding: 5px; width: 100%;">	
								{{ form.subtitulo }}
							</div>
						</div>

						<div class="clearfix" style="height:40px;"></div>

						<div id="imagenes" class="col-md-12 col-sm-12 col-xs-12">							
							<div contenedor=".contenedorMultimedia" funcion="addBannerMultimedia" class="form-group has-feedback obj tituloselect btnSelMultimedia" style="width:300px; cursor:pointer;">
								Cargar Imágen o Video
								<span class="fa fa-upload form-control-feedback right" aria-hidden="true" style="margin: 5px 9px;"></span>
							</div>
							<div style="width:100%; overflow-x:auto; max-height:750px;">
								<div class="contenedorMultimedia" style="width:100%;"></div>
							</div>
						</div>

						<input type="submit" id="submitBanner" name="submitBanner" class="btn btn-default right btnAceptar" value="Guardar" style="float:right;">

						<input type="reset" id="limpiar" class="btn right btnLimpiar" value="Limpiar" style="float:right;">
					</form>
				</div>

			</div>

			<div class="clearfix" style="height:40px;"></div>

			<div class="row divListadoForm">
				<input type="button" class="btn btn-default right btnNuevoForm" value="Nuevo" style="float:left;" ocultar="divListadoForm" mostrar="contenedorTab">

				<div class="clearfix" style="height:40px;"></div>

				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div  class="table-responsive">
						{{ datatable }}
					</div>
				</div>
			</div>
		</div>
	  </div>
	</div>

	</div>

	<div class="ItemMultimedia ItemBannerMultimedia" clon="0" style="display:none; max-width: 900px;">
		<div class="divImgBanner" style="width:650px; float:left; text-align:center;">
			<img src="" alt="">
			<span class="fa fa-close" onClick="removerMultimediaDelContenedor(this);"></span>
			<div class="clearfix"></div>
			<label class="nombreImg"  style="font-size: 15px !important;"></label>
		</div>
		
		<div class="divInfoBanner" style="width:200px; float:left; margin-left:20px; padding:10px; font-size: 15px !important;">
			<input name="id_multimedia[]" type="hidden" value="">
			<input name="activo[]" type="hidden" value="1">

			<div style="width:100%; float:left; text-align: justify;">
				<label class="labelObj" style="font-size: 15px !important;"> Activo </label>
				<div class="clearfix"></div>
				<div class="toggle toggle-light"></div>
			</div>

			<div style="width:100%; float:left; text-align: justify;">
				<label class="labelObj" style="font-size: 15px !important;"> Posición </label>
				<div class="clearfix"></div>
				<input type="number" min="1" name='posicion'>
			</div>
		</div>

	</div>

{% include "partials/multimedia.html" %}

{% endblock %}

apps/administrador/templates/clave_confirmar.html
{% extends 'inicio_sesion.html' %}

{% block center %}

{% if validlink %}

<p>Nueva contraseña</p>

<form method="post" style="width:30%;margin: auto;">
{% csrf_token %}

{{ form.new_password1.errors }}
<label for="id_new_password1">Nueva contraseña:</label>
{{ form.new_password1 }}

{{ form.new_password2.errors }}
<label for="id_new_password2">Confirme contraseña:</label>{{ form.new_password2 }}
<input type="submit" class="button_2" style="margin-top: 10px;" value="Guardar" />
</form>

{% else %}

<h1 class="text-center">ENLACE INVÁLIDO: ESTE ENLACE YA HA SIDO UTILIZADO</h1>

{% endif %}

{% endblock %}

apps/administrador/templates/clave_enviado.html
{% extends 'login.html' %}

{% block center %}

<h2>Te hemos enviado un correo con un enlace para reestablecer tu contraseña</h2>

<a href="/administrador" style="color:#585858"><h3> <i class="fa fa-caret-left"></i>  Ir al Inicio </h3>  </a>


{% endblock %}

apps/administrador/templates/index.html
{% extends 'layouts/default.html' %}
{% load staticfiles %}

{% block title %}
    Inicio
{% endblock title %}

{% block contenido %}
	<center>
		<img style="max-width: 100%;" src="{% static 'img/fondolcmundo2.png' %}" />
	</center>
{% endblock %}

apps/administrador/templates/oportunidad_empleo.html
{% extends 'layouts/default.html' %}
{% load static %}
{% load i18n %}

{% block contenido %}
  <div class="" role="tabpanel" data-example-id="togglable-tabs">
    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#contCompSocial" id="tabCompSocial" role="tab" data-toggle="tab" aria-expanded="true"> Oportunidad de Empleos </a>
      </li>
    </ul>
    
    <div id="myTabContent" class="tab-content col-md-12 col-sm-12 col-xs-12">
      <div class="clearfix"></div>
      <div class="barra"></div>

      <div role="tabpanel" class="tab-pane fade in col-md-12 col-sm-12 col-xs-12 active" id="contCompSocial" aria-labelledby="tabCompSocial">
          <div class="barra"></div>
        <div class="contenedorTab" style="display:none;">
              <input type="button" class="btn btn-default right btnVolverListado" value="Volver al Listado" style="float:left;" ocultar="contenedorTab" mostrar="divListadoForm">
          <div class="clearfix"></div>
          
          <form id="formulario" method="post" accept-charset="utf-8">
            {% csrf_token %}

            <div class="obj col-md-4 col-sm-4 col-xs-12">
            <label for="id_pais" class="labelobj"> {{ form.oficina.label }} </label>
            {{ form.oficina }}
          </div>

          <div class="obj col-md-12 col-sm-12 col-xs-12">
            <label for="id_titulo" class="labelobj"> {{ form.vacante.label }} </label>
            {{ form.vacante }}
          </div>

          <div class="obj col-md-12 col-sm-12 col-xs-12">
            <label for="id_titulo" class="labelobj"> {{ form.descripcion.label }} </label>
            {{ form.descripcion }}
          </div>

          <input id="btnAceptar" type="submit" class="btn btn-default right btnAceptar" value="Aceptar" style="margin: 20px 5px;">
          <input type="reset" id="limpiar" class="btn right btnLimpiar" value="Limpiar" style="margin: 20px 5px;">
          </form>

        </div>

        <div class="row divListadoForm">
        <input type="button" class="btn btn-default right btnNuevoForm" value="Nuevo" style="float:left;" ocultar="divListadoForm" mostrar="contenedorTab">

        <div class="clearfix" style="height:40px;"></div>

        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div  class="table-responsive">
            {{ datatable }}
          </div>
        </div>
      </div>

      </div>
    </div>
  </div>
  
{% endblock %}