LC/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from apps.administrador.views.login import cerrar_session
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    # url(r'^admin/', admin.site.urls), no se usara el admin de django
    url(r'^reset/password_reset', password_reset,
        {'template_name':'clave_formulario.html',
        'email_template_name': 'clave_correo.html'},
        name='password_reset'),
    url(r'^password_reset_done', password_reset_done,
        {'template_name': 'clave_enviado.html'},
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'clave_confirmar.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'clave_cambiada.html'},
        name='password_reset_complete'),
        url(r'^administrador/', include('apps.administrador.urls', namespace='administrador')),
        url(r'^', include('apps.website.urls', namespace='website')),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),

    #url(r'^', include('restthumbnails.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/administrador/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from .views.login import IndexView, cerrar_session, Cambiar_claveView, AceptarTerminosView

from .views.AgradecimientosView import Agradecimientos, AgradecimientosDetail, AgradecimientosCreate, AgradecimientosUpdate, AgradecimientosDelete
from .views.BannersView import Banners, BannersDetail, BannersCreate, BannersUpdate, BannersDelete
from .views.CategoriasView import Categorias, CategoriasCreate, CategoriasArbol
from .views.EstudiaTrabajaView import EstudiaTrabaja, EstudiaTrabajaDetail, EstudiaTrabajaCreate, EstudiaTrabajaUpdate, EstudiaTrabajaDelete
from .views.InformacionView import Informacion, InformacionDetail, InformacionCreate, InformacionUpdate, InformacionDelete
from .views.MultimediaView import MultimediaView, MultimediaInfoView, MultimediaListaView
from .views.OficinasView import Oficinas, OficinasDetail, OficinasCreate, OficinasUpdate, OficinasDelete, OficinasCiudades, OficinasMutimedia
from .views.Oportunidad_empleoView import Oportunidad_empleo, Oportunidad_empleoDetail, Oportunidad_empleoCreate, Oportunidad_empleoUpdate, Oportunidad_empleoDelete
from .views.Oportunidad_empleo_postuladosView import Oportunidad_empleo_postulados, Oportunidad_empleo_postuladosDetail, Oportunidad_empleo_postuladosCreate, Oportunidad_empleo_postuladosUpdate, Oportunidad_empleo_postuladosDelete
from .views.PerfilesView import Perfiles, PerfilesDetail, PerfilesCreate, PerfilesUpdate, PerfilesDelete, PerfilesArbol
from .views.Preguntas_frecuentesView import Preguntas_frecuentes, Preguntas_frecuentesDetail, Preguntas_frecuentesCreate, Preguntas_frecuentesUpdate, Preguntas_frecuentesDelete
from .views.Quienes_somosView import Quienes_somos, Quienes_somosCreate, Quienes_somosUpdate
from .views.Responsabilidad_socialView import Responsabilidad_social, Responsabilidad_socialDetail, Responsabilidad_socialCreate, Responsabilidad_socialUpdate, Responsabilidad_socialDelete
from .views.ServiciosView import Servicios, ServiciosDetail, ServiciosCreate, ServiciosUpdate, ServiciosDelete, ServiciosTipo
#from .views.SocialView import Social, SocialDetail, SocialCreate, SocialUpdate, SocialDelete
from .views.TestimoniosView import Testimonios, TestimoniosDetail, TestimoniosCreate, TestimoniosUpdate, TestimoniosDelete
from .views.UbicacionCategoriasView import UbicacionCategorias, UbicacionCategoriasDetail, UbicacionCategoriasCreate, UbicacionCategoriasUpdate, UbicacionCategoriasDelete
from .views.UbicacionView import Ubicacion, UbicacionPaisCreate, UbicacionCiudadCreate, UbicacionCiudades
from .views.UsuariosView import Usuarios, UsuariosDetail, UsuariosCreate, UsuariosUpdate, UsuariosDelete
from .views.SugerenciasView import Sugerencias, SugerenciasDetail, SugerenciasCreate, SugerenciasUpdate, SugerenciasDelete
from .views.AlojamientosView import Alojamientos, AlojamientosDetail, AlojamientosCreate, AlojamientosUpdate, AlojamientosDelete
from .views.EventosView import Eventos, EventosDetail, EventosCreate, EventosUpdate, EventosDelete
from .views.InstitucionesView import Instituciones, InstitucionesDetail, InstitucionesCreate, InstitucionesUpdate, InstitucionesDelete
from .views.NoticiaAdminView import NoticiaAdmin, NoticiaAdminDetail, NoticiaAdminCreate, NoticiaAdminUpdate, NoticiaAdminDelete

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),
    url(r'^cambiar_clave/$', Cambiar_claveView.as_view(), name='cambiar_clave'),

    url(r'^aceptar-terminos/$', AceptarTerminosView.as_view(), name='aceptar-terminos'),

    #usuarios
    url(r'^usuarios/', include([
        url(r'^$',                       Usuarios.as_view(),       name='usuarios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', UsuariosDetail.as_view(), name='usuarios-detail'),
        url(r'^create/$',                UsuariosCreate.as_view(), name='usuarios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', UsuariosUpdate.as_view(), name='usuarios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', UsuariosDelete.as_view(), name='usuarios-delete'),
    ])),

    url(r'^perfiles/', include([
        url(r'^$',                       Perfiles.as_view(),       name='perfiles'),
        url(r'^detail/(?P<pk>[0-9]+)/$', PerfilesDetail.as_view(), name='perfiles-detail'),
        url(r'^create/$',                PerfilesCreate.as_view(), name='perfiles-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', PerfilesUpdate.as_view(), name='perfiles-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', PerfilesDelete.as_view(), name='perfiles-delete'),
        url(r'^arbol/$',                 PerfilesArbol.as_view(), name='perfiles-arbol'),
    ])),
    
    url(r'^banners/', include([
        url(r'^$',                       Banners.as_view(),       name='banners'),
        url(r'^detail/(?P<pk>[0-9]+)/$', BannersDetail.as_view(), name='banners-detail'),
        url(r'^create/$',                BannersCreate.as_view(), name='banners-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', BannersUpdate.as_view(), name='banners-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', BannersDelete.as_view(), name='banners-delete'),
    ])),

    #testimonios
    url(r'^testimonios/', include([
        url(r'^$',                       Testimonios.as_view(),       name='testimonios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', TestimoniosDetail.as_view(), name='testimonios-detail'),
        url(r'^create/$',                TestimoniosCreate.as_view(), name='testimonios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', TestimoniosUpdate.as_view(), name='testimonios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', TestimoniosDelete.as_view(), name='testimonios-delete'),
    ])),
    
    #estudia_trabaja
    url(r'^estudia-trabaja/', include([
        url(r'^$',                       EstudiaTrabaja.as_view(),       name='estudia-trabaja'),
        url(r'^detail/(?P<pk>[0-9]+)/$', EstudiaTrabajaDetail.as_view(), name='estudia-trabaja-detail'),
        url(r'^create/$',                EstudiaTrabajaCreate.as_view(), name='estudia-trabaja-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', EstudiaTrabajaUpdate.as_view(), name='estudia-trabaja-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', EstudiaTrabajaDelete.as_view(), name='estudia-trabaja-delete'),
        #url(r'^ciudades/(?P<pk>[A-Z]{3})/$', EstudiaTrabajaCiudades.as_view(), name='estudia-trabaja-ciudades'),
    ])),
    
    #ubicacion
    url(r'^ubicacion/', include([
        url(r'^$',                           Ubicacion.as_view(),       name='ubicacion'),
        url(r'^pais/create/$',               UbicacionPaisCreate.as_view(), name='ubicacion-pais-create'),
        url(r'^ciudad/create/$',             UbicacionCiudadCreate.as_view(), name='ubicacion-ciudad-create'),
        url(r'^ciudades/(?P<pk>[A-Z]{3})/$', UbicacionCiudades.as_view(), name='ubicacion-ciudades'),
    ])),

    #categorias
    url(r'^categorias/', include([
        url(r'^$',                       Categorias.as_view(),       name='categorias'),
        url(r'^create/$',                CategoriasCreate.as_view(), name='categorias-create'),
        url(r'^arbol/$',                 CategoriasArbol.as_view(),  name='categorias-arbol'),
    ])),

    #servicios
    url(r'^servicios/', include([
        url(r'^$',                       Servicios.as_view(),       name='servicios'),
        url(r'^detail/(?P<pk>[0-9]+)/$', ServiciosDetail.as_view(), name='servicios-detail'),
        url(r'^create/$',                ServiciosCreate.as_view(), name='servicios-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', ServiciosUpdate.as_view(), name='servicios-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', ServiciosDelete.as_view(), name='servicios-delete'),
        url(r'^add_tipo/$',              ServiciosTipo.as_view(),   name='servicios-tipo'),
    ])),
    
    #Quienes_somos
    url(r'^quienes_somos/', include([
        url(r'^$',                       Quienes_somos.as_view(),       name='quienes_somos'),
        url(r'^create/$',                Quienes_somosCreate.as_view(), name='quienes_somos-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', Quienes_somosUpdate.as_view(), name='quienes_somos-update'),
    ])),
    
    url(r'^responsabilidad_social/', include([
        url(r'^$',                       Responsabilidad_social.as_view(),       name='responsabilidad_social'),
        url(r'^detail/(?P<pk>[0-9]+)/$', Responsabilidad_socialDetail.as_view(), name='responsabilidad_social-detail'),
        url(r'^create/$',                Responsabilidad_socialCreate.as_view(), name='responsabilidad_social-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', Responsabilidad_socialUpdate.as_view(), name='responsabilidad_social-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', Responsabilidad_socialDelete.as_view(), name='responsabilidad_social-delete'),
    ])),

    url(r'^agradecimientos/', include([
        url(r'^$',                       Agradecimientos.as_view(),       name='agradecimientos'),
        url(r'^detail/(?P<pk>[0-9]+)/$', AgradecimientosDetail.as_view(), name='agradecimientos-detail'),
        url(r'^create/$',                AgradecimientosCreate.as_view(), name='agradecimientos-create'),
        url(r'^update/(?P<pk>[0-9]+)/$', AgradecimientosUpdate.as_view(), name='agradecimientos-update'),
        url(r'^delete/(?P<pk>[0-9]+)/$', AgradecimientosDelete.as_view(), name='agradecimientos-delete'),
    ])),
    
    url(r'^multimedia/', include([
        url(r'^$',                       MultimediaView.as_view(),      name='multimedia'),
        url(r'^info/$',                  MultimediaInfoView.as_view(),  name='multimedia-info'),
        url(r'^refrescar/$',             MultimediaListaView.as_view(), name='multimedia-refrescar'),
    ])),

    url(r'^oficinas/', include([
        url(r'^$',                           Oficinas.as_view(),       name='oficinas'),

apps/website/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from .views.login import IndexView, cerrar_session, cambiar_clave
from .views.HomeView import HomeView
from .views.AlojamientosView import AlojamientosView, AlojamientosCategorias, AlojamientosDetalle, get_cities_by_countryid
from .views.NoticiasView import NoticiasView
from .views.EstudiaTrabajaView import EstudiaTrabajaView
from .views.InstitucionView import InstitucionView, InstitucionDetalle

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^cerrar_sesion/$', cerrar_session, name='cerrar_sesion'),
    url(r'^cambiar_clave/$', cambiar_clave, name='cambiar_clave'),

    #alojamientos
    url(r'^alojamientos/',
        include([
            url(r'^$', AlojamientosView.as_view(), name='alojamientos'),
            url(
                r'^categorias$',
                AlojamientosCategorias.as_view(),
            name='alojamientos-categorias'),
            url(
                r'^detail/(?P<pk>[0-9]+)/$',
                AlojamientosDetalle.as_view(),
                name='alojamientos-detail'),
            url(
                r'^get_cities/$',
                get_cities_by_countryid,
                name='obtener-ciudades'),
        ])
    ),
    #noticias
    url(r'^noticias/', NoticiasView.as_view(), name='noticias'),
    url(r'^estudia_trabaja/', EstudiaTrabajaView.as_view(), name='estudia_trabaja'),
    #instituciones
    url(r'^instituciones/',
        include([
            url(r'^$', InstitucionView.as_view(), name='instituciones'),
            url(
            r'^detail/(?P<pk>[0-9]+)/$',
            InstitucionDetalle.as_view(),
            name='instituciones-detail')
        ])
    ),
]

apps/administrador/views/UbicacionView.py
# Dependencias Django
from django.conf import settings
from django.views.generic.base import TemplateView
from django.http import JsonResponse

# Dependencias
from braces.views import LoginRequiredMixin, PermissionRequiredMixin

from apps.datatableview import columns
from apps.datatableview.datatables import Datatable

# Vista Generica
from ..vista import Vista, IndexDatatableView, DetailView, CreateView, UpdateView, DeleteView

# Formularios
from ..forms.UbicacionForm import PaisForm, CiudadForm

# Modelos
from ..models import Paises, Ciudades


class UbicacionView(LoginRequiredMixin, PermissionRequiredMixin, Vista):
    template_name = None

    model = Ciudades
    form_class = CiudadForm


class Ubicacion(UbicacionView, TemplateView):
    template_name = "ubicacion.html"

    permission_required = ['view_ubicacion']

    librerias = ['bootstrap-select']

    css = ['Ubicacion.css']
    js = ['Ubicacion.js']


class UbicacionPaisCreate(UbicacionView, CreateView):
    permission_required = ['add_ubicacion']

    form_class = PaisForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if not form.is_valid():
            return JsonResponse(form.errors, status=422)
        
        form.save()

        paises = Paises.objects.all()
        
        resultado = {'_' : ''}

        for pais in paises:
            resultado[pais.id] = pais.pais

        return JsonResponse({
            's' : 's',
            'lista' : resultado
        })

class UbicacionCiudadCreate(UbicacionView, CreateView):
    permission_required = ['add_ubicacion']

    def post(self, request, *args, **kwargs):
        ciudad = Ciudades(pais_id=request.POST.get('pais'), ciudad=request.POST.get('ciudad'))
        ciudad.save()

        pais_id = request.POST.get('pais', '')
        ciudades = Ciudades.objects.filter(pais_id=id).order_by('-ciudad')
        resultado = {'_' : ''}

        for ciudad in ciudades:
            resultado[ciudad.id] = ciudad.ciudad

        return self.response({
            'lista' : resultado
        })

class UbicacionCiudades(UbicacionView, DetailView):
    permission_required = ['detail_-']

    def get(self, request, *args, **kwargs):
        id = self.kwargs.get('pk', '')
        ciudades = Ciudades.objects.filter(pais_id=id).order_by('-ciudad')
        resultado = {'_' : ''}

        for ciudad in ciudades:
            resultado[ciudad.id] = ciudad.ciudad
        
        return JsonResponse({
            'id_ciudad' : resultado
        })

apps/website/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponse
# Create your views here.

def index(request):
    if request.user.is_authenticated():
        return render(request, 'base.html')
    else:
        if request.method == 'POST':
            if iniciar_sesion(request):
                if request.GET:
                    return HttpResponseRedirect(request.GET.get('next'))
                else:
                    return render(request, 'base.html')
            else:
                return render(request, 'inicio_sesion.html')

    return render(request, 'inicio_sesion.html')

def iniciar_sesion(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return True
        else:
            messages.add_message(request, messages.INFO,
                                 _('Cuenta de usuario inactiva'))
            return False
    else:
        messages.add_message(request, messages.INFO, _(
            'Nombre de usuario o contraseña no válido'))

def crear_usuario(request):
    return render(request, 'usuarios.html')

def banners(request):
    return render(request, 'banners.html')

def testimonios(request):
    return render(request, 'testimonios.html')

def estudia_trabaja(request):
    return render(request, 'estudia_trabaja.html')

def ubicacion_categorias(request):
    return render(request, 'ubicacion_categorias.html')

def servicios(request):
    return render(request, 'servicios.html')
def cerrar_sesion(request):
    logout(request)
    return redirect('/administrador/')

apps/website/templates/partials/buscador.html
{% load staticfiles %}
{% load i18n %}
<div class="verde">
	<div class="container">
		<div class="row" style="padding: 10px">
			<form action="#">
				<div class="col-md-2 col-xs-12"></div>
				<div class="col-md-2 col-xs-12" style="padding:10px;">
					<select name="categorias" class="form-control campo" id="id_categorias" required="" placeholder="categorias" tabindex="-98">
						<option value="" selected="">{{ _('Categoria') }}</option>
						{% for categoria in categorias %}
							<option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
						{% endfor %}
					</select>
				</div>					
				<div class="col-md-2 col-xs-12" style="padding:10px;">
					<select name="pais" class="form-control campo" id="id_paises" required="" placeholder="pais" tabindex="-98">
						<option value="" selected="">{{ _('Pais') }}</option>
						{% for pais in ciudades %}
							<option value="{{ pais.id }}">{{ pais.nombre }}</option>
						{% endfor %}
					</select>
				</div>					
				
				<div class="col-md-2 col-xs-12" style="padding:10px;">
					<select name="ciudades" class="form-control campo" id="id_ciudades" required="" placeholder="ciudades" tabindex="-98">
						<option value="" selected="">{{ _('Ciudad') }}</option>
					</select>
				</div>
				<div class="col-md-2 col-xs-12" style="padding:10px;">
					<!--<input type="button" id="btnBuscar" class="btn btn-default btn-buscar" value="BUSCAR">-->
					<a href="{% url 'website:instituciones' %}">
						<span class="btn btn-default btn-buscar">BUSCAR</span>
					</a>
				</div>
				<div class="col-md-2 col-xs-12"></div>
			</form>
		</div>
	</div>
</div>

apps/website/templates/partials/menu_front.html
{% load staticfiles %}
{% load i18n %}

<header id="headerMenu">
  <nav class="navbar navbar-default barratop" role="navigation" style="min-height:30px;">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#search" style="float:left;" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <button type="button" class="navbar-toggle right" data-toggle="collapse" data-target="#links" style="float:right;" aria-expanded="true">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-option-vertical"></span>
        </button>

      </div>
        <ul class="navbar-collapse nav navbar-nav col-xs-12 collapse in" id="links" style="width: 100%;" aria-expanded="true">

            <li> 
                <a href="#" class="link_icon" id="btnidioma" data-toggle="dropdown" aria-expanded="false"> 
                    ES <span class="glyphicon glyphicon-globe"></span> 
                </a> 

                <ul class="dropdown-menu"  role="menu" aria-labelledby="btnidioma">
                    <li><a href="#">EN</a></li>
                    <li><a href="#">PR</a></li>
                </ul>
            </li>
            <li>
                <a href="#" class="link_icon"> <span class="glyphicon glyphicon-search"></span> </a>
            </li>
            <li style="display:none; width:100%; float:right;" class="liseparador"></li>
            <li style="float:right;">
                <a id="linkayuda" href="#" class="dropdown-toggle link_icon" id="menu1" data-toggle="dropdown" aria-expanded="false"> Ayuda <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                    <li><a href="#">{{ _('Preguntas Frecuentes') }}</a></li>
                    <li><a href="#">{{ _('Sugerencias y reclamos') }}</a></li>
                    
                </ul>                
            </li>
            <li style="float:right;">
                <a href="#" class="link_icon">  {{ _('Registrate') }} </a>
            </li>
            <li style="float:right;">
                <a href="#" class="link_icon"> {{ _('Iniciar Sesión') }} </a>
            </li>

            <li style="display:none; width:100%; float:right;" class="liseparador"></li>

            <li style="float:right;">
                <a href="#" class="link_icon"> <span class="fa fa-instagram"></span> </a>
            </li>
            <li style="float:right;">
                <a href="#" class="link_icon"> <span class="fa fa-twitter"></span> </a>
            </li>
            <li style="float:right;">
                <a href="#" class="link_icon"> <span class="fa fa-facebook"></span> </a>
            </li>
        </ul>

    </div>
  </nav>

  <nav class="verde col-lg-12 col-md-12 col-sm-12 col-xs-12 navlogo">
        <img src="{% static 'img/lc_blanco_90.png' %}" class="img-responsive" style="max-width:100%;padding: 20px;margin: auto;">
  </nav>

  <nav class="navbar navbar-default nav2 col-xs-12" role="navigation" style="z-index:2;border-bottom:1px solid #425166">
    <div class="container">
        <div class="row">
            <ul class="navbar-collapse nav navbar-nav navbar-center collapse" id="search" role="navigation" aria-expanded="false" style="float:none;">
                <li class="col-lg-1 col-md-1 col-sm-1 col-xs-6"> 
                    <a href="{% url 'website:home' %}" id="linkHome"> 
                        <img src="{% static 'img/logolc110.png' %}" style="max-width:100%; margin:auto; display:none;" id="logoNavBlanco">
                        <span> {{ _('Inicio') }} </span>
                    </a> 
                </li>

                <li class="dropdown col-lg-2 col-md-2 col-sm-2 col-xs-6">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> {{ _('Instituciones') }} <b class="caret"></b> </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'website:instituciones' %}">{{ _('Instituciones') }}</a></li>
                        <li><a href="#">{{ _('Cursos') }}</a></li>
                    </ul>
                </li>

                <li class="dropdown col-lg-2 col-md-2 col-sm-2 col-xs-6">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">{{ _(' Vive y Trabaja') }} <b class="caret"></b> </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'website:alojamientos' %}">{{ _('Alojamientos') }}</a></li>
                        <li><a href="{% url 'website:estudia_trabaja' %}">{{ _('Estudia y Trabaja') }}</a></li>
                        <li><a href="#">{{ _('Eventos') }}</a></li>
                    </ul>
                </li>

                <li class="dropdown col-lg-2 col-md-2 col-sm-2 col-xs-6">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> {{ _('Servicios') }} <b class="caret"></b> </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Servicios 1</a></li>
                        <li><a href="#">Servicios 2</a></li>
                        <li><a href="#">Servicios 3</a></li>
                    </ul>
                </li>

                <li class="dropdown col-lg-2 col-md-2 col-sm-2 col-xs-6">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> {{ _('Sobre Nosotros') }} <b class="caret"></b> </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">{{ _('Quienes somos') }}</a></li>
                        <li><a href="#">{{ _('Responsabilidad social') }}</a></li>
                        <li><a href="#">{{ _('Agradecimientos') }}</a></li>
                    </ul>
                </li>

                <li class="dropdown col-lg-2 col-md-2 col-sm-2 col-xs-6">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> {{ _('Contáctanos') }} <b class="caret"></b> </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">{{ _('Oficinas') }}</a></li>
                        <li><a href="#">{{ _('Oportunidad de Empleo') }}</a></li>
                        <li><a href="#">{{ _('Solicitud de Información') }}</a></li>
                    </ul>
                </li>
                <li class="dropdown col-lg-1 col-md-1 col-sm-1 col-xs-6">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="color: #c3d245; font-size: 22px;"> 
                       <span class="glyphicon glyphicon-folder-close"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="#">Notificación 1</a></li>
                        <li><a href="#">Notificación 2</a></li>
                        <li><a href="#">Notificación 3</a></li>
                    </ul>
                </li>
            </ul>
            
        </div> 
    </div>
  </nav>
      
</header>